### ISSUE TITLE
More visible/faster picture mode

### ISSUE THREAD

**Issue by MarkHolton** [CMMS/Systemiser-Support#2]
See the attached Excel file for a faster way to jump between and close down cards in picture mode, also keep all reduced cards visible
[PictureModeExpandingBoes.xlsx](https://github.com/CMMS/Systemiser-Support/files/1105643/PictureModeExpandingBoes.xlsx)

**Comment by SlicedSilver** [comment]
https://github.com/CMMS/PaperGalaxy/issues/273
